backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: case-study
    label: Case Study
    format: json
    folder: assets/content/case-study
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - name: title
        label: Title
        widget: string

      - name: category
        label: Category
        widget: select
        options: ['Product Design', 'Brand Identity', 'Motion Design']

      - name: thumbnail
        label: Thumbnail
        widget: image
        allow_multiple: false

      - name: feature
        label: Feature
        widget: image
        allow_multiple: false

      - name: description
        label: Description
        widget: string
        
      - name: duration
        label: Duration
        widget: string

      - name: role
        label: Role
        widget: string

      - name: for
        label: For
        widget: string

      - name: color
        label: Color
        widget: string
        hint: 'Use a HEX code that does not contain #'
        pattern: ['/^([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/igm', 'Must be a valid HEX code, without #']

      - name: section
        label: Section
        widget: list
        fields:
          - name: content
            label: Content
            widget: markdown
